[package]
name = "semantic_term_processor"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pulldown-cmark = "0.9"
sophia_term = { path = "../../vendor/sophia_rs/term" }
sophia_iri = { path = "../../vendor/sophia_rs/iri" }
sophia_api = { path = "../../vendor/sophia_rs/api" }
sophia_turtle = { path = "../../vendor/sophia_rs/turtle" }