[package]
name = "signals_lib"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
solfunmeme_dioxus_deps = { path = "../solfunmeme_dioxus_deps" }
serde = { version = "1.0", features = ["derive"] }
shared_types_lib = { path = "../../layer1_physical/shared_types_lib" }
fastrand = "2.0"
solfunmeme_rdf_utils = { path = "../../../../crates/layer6_presentation/solfunmeme_rdf_utils" } 