[package]
name = "ragit-prompt-management"
version = "0.1.0"
edition = "2021"

[dependencies]
ragit-types = { path = "../ragit-types" }


ragit-fs = { path = "../fs" }
ragit-utils = { path = "../ragit-utils" }
anyhow = "1.0"
