[package]
name = "ragit-command-change-request"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
ragit-qa-qm = { path = "../../ragit-qa-qm" }
