[package]
name = "ragit-index-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
ragit-types = { path = "../../layer1_physical/ragit-types" }
ragit-model = { path = "../../layer7_application/ragit-model" }
ragit-utils = { path = "../../layer3_network/ragit-utils" }
ragit-error = { path = "../../layer1_physical/ragit-error" }
ragit-config = { path = "../../layer5_session/ragit-config" }
ragit-api = { path = "../../layer7_application/api" }
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
ragit-tfidf = { path = "../ragit-tfidf" }
tokio = { version = "1.0", features = ["full"] }
ragit-fs = { path = "../../layer2_data_link/fs" }
sha3 = "0.10.8"


ragit-ignore = { path = "../../layer2_data_link/ignore" }
ragit-model-query-response = { path = "../../layer6_presentation/ragit-model-query-response" }

[features]
default = []
index = []
all = ["index"]