[package]
name = "ragit-social-twitter"
version = "0.1.0"
edition = "2021"

[dependencies]
egg-mode = "0.16.1"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }