[package]
name = "term_quiz_master"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
clap = { version = "4.0", features = ["derive"] }
git2 = "0.19"
toml = { version = "0.8" }
tokio = { version = "1", features = ["full"] }
# hf-dataset-validator = { path = "../../vendor/meta-introspector/hugging-face-dataset-validator-rust" }

