[package]
name = "solfunmeme_core_logic"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
sophia_turtle = "0.8"
sophia_api = "0.8"
sophia_inmem = "0.8"
syn-serde = { git = "https://github.com/meta-introspector/syn-serde-rust", branch="main", features = ["json"] }

inventory = "0.3"
zip = { version = "0.6" , default-features=false }
bincode = "1.3.3"
bip39 = "2.1.0"
bs58 = "0.5.1"
chacha20poly1305 = "0.10.1"
chrono = "0.4.41"
console_log = "1.0.0"
log = "0.4.21"
markdown-meta-parser = "0.1.3"
nalgebra = "0.33.2"
nom = "8.0.0"
percent-encoding = "2.3.1"
pulldown-cmark = "0.13.0"
regex = "1.10.4"
ring = { version = "0.17.14", features = ["wasm32_unknown_unknown_js"] }
ring-compat = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
aes-gcm = "0.10.3"
base64 = "0.22.1"
serde_json = "1.0"
sha2 = "0.10.9"
easer = "0.3.0"
syn = "2.0.103"
thiserror = { version = "2.0.12" }
url = "2.5.4"
wasm-logger = "0.2.0"

ndarray = "0.15.6"
tclifford = { path = "../../../vendor/meta-introspector/solfunmeme-dioxus/vendor/tclifford" }
linfa = "0.7.1"
linfa-preprocessing = "0.7.1"
linfa-reduction = "0.7.1"
linfa-clustering = "0.7.1"
rust-embed = { version = "8.7.2", features = ["debug-embed"] , path = "../../../vendor/rust-embed"}
fastrand = "2.0.1"
getrandom = { version = "0.3.3", features = ["wasm_js"] }
rand = "0.8.5"
rand_core = { version = "0.6.4", features = ["std"] }
emojis = "0.7.0"
csv = "1.3.1"
markdown = "1.0.0"
urlencoding = "2.1.3"
scraper = "0.23.1"
rrust_kontekst = {path = "../../../vendor/meta-introspector/solfunmeme-dioxus/crates/rrust_kontekst"}
#orbital_sim_lib = {path = "../../../vendor/meta-introspector/solfunmeme-dioxus/crates/orbital_sim_lib"}
#core_data_lib = {path = "../../../vendor/meta-introspector/solfunmeme-dioxus/crates/core_data_lib"}
#emoji_matrix_lib = {path = "../../../vendor/meta-introspector/solfunmeme-dioxus/crates/emoji_matrix_lib"}
rrust_kontekst_base = {path = "../../../vendor/meta-introspector/solfunmeme-dioxus/crates/rrust_kontekst_base"}
solfunmeme_extractor = {path = "../../../vendor/meta-introspector/solfunmeme-dioxus/crates/solfunmeme_extractor"}
#component_builder_lib = {path = "../../../vendor/meta-introspector/solfunmeme-dioxus/crates/component_builder_lib"}
#component_registry_lib = {path = "../../../vendor/meta-introspector/solfunmeme-dioxus/crates/component_registry_lib"}
#component_emoji_lib = {path = "../../../vendor/meta-introspector/solfunmeme-dioxus/crates/component_emoji_lib"}
#playground_lib = {path = "../../../vendor/meta-introspector/solfunmeme-dioxus/crates/playground_lib"}
views_lib = {path = "../../../vendor/meta-introspector/solfunmeme-dioxus/crates/views_lib"}
solfunmeme_models = {path = "../../../vendor/meta-introspector/solfunmeme-dioxus/crates/solfunmeme_models"}
shared_types_lib = {path = "../../../vendor/meta-introspector/solfunmeme-dioxus/crates/shared_types_lib"}
signals_lib = {path = "../../../vendor/meta-introspector/solfunmeme-dioxus/crates/signals_lib"}
ctor = "0.4.2"
tracing = "0.1.41"
curve25519-dalek = "4.1.3"
walkdir = "2.5.0"


[dependencies.x25519-dalek  ]
version = "2.0.1"
features = [ "static_secrets"]

[dependencies.uuid]
version = "1.17.0"
features = [
    "v4",
    "js",
    "rng-getrandom",
    "rng-rand"
]

# [dependencies.burn]
# version = "0.17.1"
# optional = true
# features = ["wgpu"]

[features]
default = []
# burn-backend = ["burn"]
