[package]
name = "ragit-chunk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
ragit-types = { path = "../../layer1_physical/ragit-types" }
ragit-error-conversions = { path = "../ragit-error-conversions" }

ragit-config = { path = "../../layer5_session/ragit-config" }
ragit-api = { path = "../../layer7_application/api" }
ragit-fs = { path = "../../layer2_data_link/fs" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha3 = "0.10.8"
tokio = { version = "1.0", features = ["full"] }
regex = "1.5"
tera = "1.17"
ragit-pdl = { path = "../../layer6_presentation/pdl" }
ragit-model = { path = "../../layer7_application/ragit-model" }
ragit-schema = { path = "../../layer6_presentation/ragit-schema" }
