[package]
name = "ragit-build-index-worker-single-file"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
sysinfo = "0.30"
glob = "0.3"
ragit-index-types = { path = "../../legacy_and_refactoring/ragit-index-types" }
ragit-types = { path = "../../layer1_physical/ragit-types" }
ragit-index-save-to-file = { path = "../../legacy_and_refactoring/ragit-index-save-to-file" }
ragit-utils = { path = "../../layer3_network/ragit-utils" }
ragit-index-core = { path = "../../legacy_and_refactoring/ragit-index-core" }
ragit-file-error = { path = "../../layer1_physical/ragit-file-error" }
ragit-index-effects = { path = "../../legacy_and_refactoring/ragit-index-effects" }
ragit-readers = { path = "../../layer4_transport/ragit-readers" }
chrono = "0.4"
serde_json = "1.0"
text-splitter = "0.3"