[package]
name = "ragit-readers"
version = "0.1.0"
edition = "2021"

[dependencies]
ragit-utils = { path = "../ragit-utils" }
ragit-fs = { path = "../fs" }
ragit-types = { path = "../ragit-types" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.11.1"
image = "0.25.6"
markdown = "1.0.0-alpha.0"
ragit-error = { path = "../ragit-error" }
ragit-pdl = { path = "../pdl" }
url = "2.5.0"
ragit-index-types = { path = "../ragit-index-types" }
ragit-chunk = { path = "../ragit-chunk" }