[package]
name = "ragit-agent-action"
version = "0.1.0"
edition = "2021"

[dependencies]
ragit-types = { path = "../../layer1_physical/ragit-types" }
ragit-index-types = { path = "../ragit-index-types" }
ragit-utils = { path = "../../layer3_network/ragit-utils" }
ragit-api = { path = "../../layer7_application/api" }
ragit-tfidf = { path = "../ragit-tfidf" }
ragit-agent = { path = "../ragit-agent" }
ragit-index-io = { path = "../ragit-index-io" }
ragit-model = { path = "../../layer7_application/ragit-model" }
anyhow = "1.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
ragit-model-query-response = { path = "../../layer6_presentation/ragit-model-query-response" }