[package]
name = "views_lib"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
dioxus = { version = "0.6.3", features = ["router"] }
core_data_lib = { path = "../../../vendor/meta-introspector/solfunmeme-dioxus/crates/core_data_lib" }
shared_types_lib = { path = "../../../crates/layer1_physical/shared_types_lib" }
signals_lib = { path = "../../../crates/layer6_presentation/signals_lib" }
