[package]
name = "ragit-hf-dataset"
version = "0.1.0"
edition = "2021"
authors = ["ragit contributors"]
description = "Hugging Face dataset generation for ragit emoji vectorization"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
arrow = "53.0"
parquet = "53.0"
uuid = { version = "1.0", features = ["v4"] }
chrono = "0.4"

# Ragit dependencies
solfunmeme_clifford = { path = "../../layer4_transport/solfunmeme_clifford" }

# HF Dataset Validator (vendored)
hf-dataset-validator = { path = "../../../vendor/hf-dataset-validator-rust" }

[dev-dependencies]
tempfile = "3.0"
