[package]
name = "ragit-command-ls"
version = "0.1.0"
edition = "2021"

[dependencies]
ragit-utils = { path = "../../../layer3_network/ragit-utils" }
ragit-api = { path = "../../api" }
ragit-types = { path = "../../../layer1_physical/ragit-types" }
ragit-index-io = { path = "../../../legacy_and_refactoring/ragit-index-io" }
ragit-index-core = { path = "../../../legacy_and_refactoring/ragit-index-core" }
ragit-query = { path = "../../../layer4_transport/ragit-query" }
ragit-cli = { path = "../../cli" }
serde_json = "1.0"
ragit-error = { path = "../../../layer1_physical/ragit-error" }
ragit-schema = { path = "../../../layer6_presentation/ragit-schema" }
ragit-tfidf = { path = "../../../layer3_network/ragit-tfidf" }
anyhow = "1.0"
async-trait = "0.1"
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
