use crate::grand_plan::ragit_chunk_integration::chunk_formal_metadata::chunk_formal_metadata_struct::ChunkFormalMetadata;

pub fn generate_formal_metadata(new_module_name: &str) -> ChunkFormalMetadata {
    ChunkFormalMetadata::new(
        format!("lean_program_{}", new_module_name),
        None, // No proof generated by default
        format!("zk_circuit_{}", new_module_name),
        rand::random::<u64>(), // Random Godel number
        format!("zkml_inference_for_{}", new_module_name),
        format!("lattice_fold_ref_{}", new_module_name),
    )
}
