[package]
name = "ragit-api"
version = "0.4.2"
edition = "2024"
license = "MIT"
description = "api utilities for ragit"
repository = "https://github.com/baehyunsol/ragit"
documentation = "https://docs.rs/ragit-api"

[dependencies]
async-std = "1.13.0"
base64 = "0.22.1"
chrono = "0.4.40"
clap = { version = "4.5.26", features = ["derive"] }
futures = "0.3.31"
image = "0.25.5"
lazy_static = "1.5.0"
ragit-fs = { path = "../../layer2_data_link/fs", version = "0.4.2", features = ["log"] }

reqwest = "0.12.12"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
strum = { version = "0.27", features = ["derive"] }
strum_macros = "0.27"
tera = "1.20.0"
thiserror = "1.0"
tokio = { version = "1.43.0", features = ["full"] }
toml = "0.8.14"
rand = "0.8"
ragit-types = { path = "../../layer1_physical/ragit-types" }
ragit-model = { path = "../ragit-model" }
ragit-core-utils = { path = "../../layer4_transport/ragit-core-utils" }
ragit-schema = { path = "../../layer6_presentation/ragit-schema" }
ragit-session-query = { path = "../../layer5_session/ragit-session-query" }
ragit-pdl = { path = "../../layer6_presentation/pdl" }
ragit-model-provider = { path = "../ragit-model-provider" }

ragit-uid = { path = "../../layer2_data_link/ragit-uid" }

