[package]
name = "ragit-dwim"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.38", features = ["full"] }
ragit-types = { path = "../../layer1_physical/ragit-types" }
ragit-utils = { path = "../../layer3_network/ragit-utils" }
# solfunmeme_embedding = { path = "../../../vendor/meta-introspector/solfunmeme-dioxus/crates/solfunmeme_embedding" }
# solfunmeme_clifford = { path = "../../../vendor/meta-introspector/solfunmeme-dioxus/crates/solfunmeme_clifford" }
# # solfunmeme_ontology_vibe = { path = "../../../vendor/meta-introspector/solfunmeme-dioxus/crates/solfunmeme_ontology_vibe" }
mownstr = { path = "../../../vendor/mownstr" }

