[package]
name = "ragit-tfidf"
version = "0.1.0"
edition = "2021"

[dependencies]
ragit-types = { path = "../../layer1_physical/ragit-types" }
ragit-error = { path = "../../layer1_physical/ragit-error" }
ragit-fs = { path = "../../layer2_data_link/fs" }
ragit-utils = { path = "../../layer3_network/ragit-utils" }
anyhow = "1.0"
flate2 = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rust-stemmers = "1.2"
