[package]
name = "ragit-command-duplicate-chunks"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
anyhow = "1.0"
tokio = { version = "1.43.0", features = ["full"] }
ragit-index-io = { path = "../../../legacy_and_refactoring/ragit-index-io" }
ragit-types = { path = "../../../layer1_physical/ragit-types" }
ragit-utils = { path = "../../../layer3_network/ragit-utils" }
ragit-index-types = { path = "../../../layer3_network/ragit-index-types" }
