[package]
name = "ragit-command-pdl"
version = "0.1.0"
edition = "2021"

[dependencies]
ragit-utils = { path = "../../../layer3_network/ragit-utils" }
ragit-api = { path = "../../api" }
ragit-types = { path = "../../../layer1_physical/ragit-types" }
ragit-index-io = { path = "../../../legacy_and_refactoring/ragit-index-io" }
ragit-index-types = { path = "../../../layer3_network/ragit-index-types" }
ragit-pdl = { path = "../../../layer6_presentation/pdl" }
ragit-schema = { path = "../../../layer6_presentation/ragit-schema" }
ragit-fs = { path = "../../../layer2_data_link/fs" }
anyhow = "1.0"
async-trait = "0.1"
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tera = "1.20"
chrono = "0.4"