[package]
name = "ragit-error-conversions"
version = "0.1.0"
edition = "2021"

[dependencies]
ragit-types = { path = "../../layer1_physical/ragit-types" }
ragit-pdl = { path = "../../layer6_presentation/pdl" }
