[package]
name = "ragit-index-save-to-file"
version = "0.1.0"
edition = "2021"

[dependencies]
ragit-types = { path = "../../layer1_physical/ragit-types" }
ragit-index-types = { path = "../../layer3_network/ragit-index-types" }
ragit-fs = { path = "../../layer2_data_link/fs" }
anyhow = "1.0"
serde_json = "1.0"