[package]
name = "ragit-session-query"
version = "0.1.0"
edition = "2021"

[dependencies]
ragit-types = { path = "../ragit-types" }
ragit-pdl = { path = "../pdl" }
ragit-utils = { path = "../ragit-utils" }
ragit-error = { path = "../ragit-error" }
ragit-core-utils = { path = "../ragit-core-utils" }
ragit-model-provider = { path = "../ragit-model-provider" }
ragit-model-query-response = { path = "../ragit-model-query-response" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"