[package]
name = "ragit-command-summary"
version = "0.1.0"
edition = "2021"

[dependencies]
ragit-cli = { path = "../../cli" }
ragit-utils = { path = "../../../layer3_network/ragit-utils" }
ragit-index-io = { path = "../../../legacy_and_refactoring/ragit-index-io" }
ragit-index-core = { path = "../../../legacy_and_refactoring/ragit-index-core" }
ragit-types = { path = "../../../layer1_physical/ragit-types" }
anyhow = "1.0"
