[package]
name = "ragit-index-model-management"
version = "0.1.0"
edition = "2021"

[dependencies]
ragit-index-types = { path = "../ragit-index-types" }
ragit-types = { path = "../../layer1_physical/ragit-types" }
ragit-index = { path = "../../layer3_network/ragit-index" }
ragit-model = { path = "../../layer7_application/ragit-model" }
ragit-utils = { path = "../../layer3_network/ragit-utils" }
ragit-fs = { path = "../../layer2_data_link/fs" }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
