[package]
name = "ragit-commands"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
anyhow = "1.0"
async-recursion = "1.1.1"
chrono = "0.4.40"
csv = { version = "1.3.1", optional = true }
image = { version = "0.25.5", default-features = false, features = ["rayon", "bmp", "dds", "exr", "ff", "gif", "ico", "jpeg", "png", "pnm", "qoi", "tga", "tiff", "webp"] }
lazy_static = "1.5.0"
regex = "1.11.1"
reqwest = { version = "0.12.12", features = ["multipart"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = { version = "1.0.139", features = ["arbitrary_precision"] }
sha3 = "0.10.8"
tera = "1.20.0"
tokio = { version = "1.43.0", features = ["full", "process"] }
url = "2.5.4"
mupdf = { version = "0.5.0", optional = true }
resvg = { version = "0.45.1", optional = true }
png = { version = "0.17.16", optional = true }

ragit-api = { path = "../../layer7_application/api" }

ragit-fs = { path = "../../layer2_data_link/fs" }
ragit-pdl = { path = "../../layer6_presentation/pdl" }
ragit-types = { path = "../../layer1_physical/ragit-types" }
ragit-utils = { path = "../../layer3_network/ragit-utils" }
ragit-index-io = { path = "../../legacy_and_refactoring/ragit-index-io" }
ragit-index = { path = "../../layer3_network/ragit-index" }
ragit-index-query = { path = "../../legacy_and_refactoring/ragit-index-query" }
ragit-query = { path = "../../layer4_transport/ragit-query" }
ragit-model-query-response = { path = "../../layer6_presentation/ragit-model-query-response" }
ragit-cli = { path = "../cli" }
ragit-command-bootstrap = { path = "../commands/ragit-command-bootstrap" }
ragit-command-duplicate-chunks = { path = "../commands/ragit-command-duplicate-chunks" }
ragit-dyim = { path = "../ragit-dyim" }
ragit-tfidf = { path = "../../layer3_network/ragit-tfidf" }
ragit-qa-system = { path = "../../legacy_and_refactoring/ragit-qa-system" }


ragit-index-types = { path = "../../layer3_network/ragit-index-types" }
ragit-memory-monitor = { path = "../../layer1_physical/ragit-memory-monitor" }
tempfile = "3.20.0"

# [dependencies.tikv-jemallocator]
# version = "0.5"
# features = ["profiling", "unprefixed_malloc_on_supported_platforms"]

[features]
default = ["csv"]
full = ["csv", "korean"]

csv = ["dep:csv"]
korean = []
pdf = ["dep:mupdf"]
svg = ["dep:resvg", "dep:png"]