[package]
name = "solfunmeme_clifford"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0"

[dependencies]
tclifford = { path = "../../../vendor/meta-introspector/solfunmeme-dioxus/vendor/tclifford" }


rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
sha2 = "0.10"
